version: '3.8'

services:
  scouty-db:
    # On utilise l'image officielle PostgreSQL version 17 (basée sur Alpine Linux, très légère)
    image: postgres:17-alpine
    
    # Le nom que tu verras dans Docker Desktop
    container_name: scouty_postgres_docker
    
    # Si le conteneur plante ou si tu redémarres Docker, il redémarre tout seul
    restart: always
    
    # Les variables d'environnement pour configurer l'utilisateur admin interne
    environment:
      - POSTGRES_USER=scouty_user
      - POSTGRES_PASSWORD=scouty_password
      - POSTGRES_DB=ScoutyDb
      
    # LE POINT CRUCIAL : MAPPING DES PORTS
    # "Port Extérieur (Ton PC) : Port Intérieur (Conteneur)"
    # On utilise 5433 sur ton PC pour ne pas heurter ton Postgres local (5432)
    ports:
      - "5433:5432"
      
    # LA PERSISTANCE DES DONNÉES
    # Sans ça, si tu supprimes le conteneur, tu perds tes tables.
    # Ici, on stocke les données dans un volume géré par Docker.
    volumes:
      - scouty_pg_data:/var/lib/postgresql/data

# Déclaration du volume
volumes:
  scouty_pg_data: