name: Build Android App

on:
  push:
    branches: [ "dev" ]
    paths:
      - 'Scouty.Frontend/**'
      - 'Scouty.Shared/**'
      - '.github/workflows/deploy-android.yml'

env:
  CheckEolTargetFramework: false
  DOTNET_MULTILEVEL_LOOKUP: 0

jobs:
  build-android:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Force la version .NET 8 stable
      - name: Create global.json
        run: |
          New-Item -Path . -Name "global.json" -ItemType "file" -Value '{ "sdk": { "version": "8.0.404", "rollForward": "latestFeature" } }' -Force

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.404

      - name: Install MAUI Workloads
        run: dotnet workload install maui --ignore-failed-sources

      # LE CORRECTIF 
      - name: Decode Keystore
        run: |
          if ("${{ secrets.ANDROID_KEYSTORE_BASE64 }}" -ne "") {
              $bytes = [System.Convert]::FromBase64String("${{ secrets.ANDROID_KEYSTORE_BASE64 }}")
              # On place le fichier là où le projet l'attend
              [IO.File]::WriteAllBytes("Scouty.Frontend/scouty.keystore", $bytes)
          } else {
              Write-Error "ERREUR CRITIQUE : Le secret ANDROID_KEYSTORE_BASE64 est vide."
              exit 1
          }

      - name: Publish Android App
        run: |
          dotnet publish Scouty.Frontend/Scouty.Frontend.csproj `
            -f net8.0-android `
            -c Release `
            -p:AndroidPackageFormat=aab `
            -p:AndroidKeyStore=true `
            -p:AndroidSigningKeyStore="scouty.keystore" `
            -p:AndroidSigningKeyAlias="${{ secrets.ANDROID_KEY_ALIAS }}" `
            -p:AndroidSigningKeyPass="${{ secrets.ANDROID_KEY_PASSWORD }}" `
            -p:AndroidSigningStorePass="${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" `
            -p:TreatWarningsAsErrors=false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Scouty-Android-Bundle
          path: Scouty.Frontend/bin/Release/net8.0-android/publish/*-Signed.aab