name: Build & Release Android App

on:
  push:
    tags:
      - "v*"

jobs:
  build-android:
    runs-on: windows-latest

    env:
      DOTNET_CLI_UI_LANGUAGE: en-US
      CheckEolTargetFramework: false

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    # On force le SDK 8 pour éviter les erreurs de version EOL
    - name: Forcer l'utilisation du SDK .NET 8
      run: dotnet new globaljson --sdk-version 8.0.100 --roll-forward latestFeature

    - name: Installer .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # CORRECTION ICI : On ajoute "maui-maccatalyst" à la liste
    - name: Installer les workloads MAUI
      run: dotnet workload install maui-android maui-ios maui-maccatalyst

    - name: Restaurer les dépendances
      run: dotnet restore Scouty.Frontend/Scouty.Frontend.csproj -p:CheckEolTargetFramework=false

    - name: Compiler et Publier l'APK
      run: |
        dotnet publish Scouty.Frontend/Scouty.Frontend.csproj -f net8.0-android -c Release -p:AndroidPackageFormats=apk -p:CheckEolTargetFramework=false --no-restore -o build_output

    - name: Créer la Release GitHub
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build_output/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}